title: Записная книжка
author: Владимир Быстрицкий
description: Компьютерное зрение, машинное обучение, нейронный сети и т.п.
email: vbystricky@gmail.com
baseurl: ""
permalink: /:year/:month/:title.html
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
excerpt_separator: <!--more-->

paginate: 5
paginate_path: "/pages/page:num/"

gems:
  - jekyll-paginate
#  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
#  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

